### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by medialwerk** [efacilitation/hubot-loggly#1]
```
[Wed Jan 25 2017 09:27:31 GMT+0100 (CET)] ERROR TypeError: Cannot read property 'forEach' of undefined
    at /app/node_modules/hubot-loggly/src/loggly.coffee:41:34
    at /app/node_modules/hubot-loggly/src/loggly.coffee:20:16
    at /app/node_modules/hubot-loggly/src/loggly.coffee:12:16
    at IncomingMessage.<anonymous> (/app/node_modules/hubot/node_modules/scoped-http-client/src/index.js:95:22)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

```

**Comment by medialwerk** [comment]
Closed https://github.com/efacilitation/hubot-loggly/commit/39ce617be8409df1891f838d25613f8c6c4a1932
